// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202012091205295_changeTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
